### ISSUE TITLE
1. As an employee of World health organisation, I require reports which organise all countries in the world, continent or region by largest population to smallest so I know where to direct resource first.

### ISSUE THREAD

**Issue by GailFairley** [GailFairley/NapierGroupF#30]

**Comment by KLazdina** [comment]
Three different reports segmented by area are made available to the employees.
Reports:
- All the countries in the world organised by largest population to smallest.
- All the countries in a continent organised by largest population to smallest.
- All the countries in a region organised by largest population to smallest.
